// @ts-check
// One auto-generated sidebar per top-level docs/ category. Each category
// folder ships with a `_category_.json` (created by the generator) and an
// `index.md` so Docusaurus can render the category landing page.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  itemsSidebar:        [{ type: 'autogenerated', dirName: 'items' }],
  spellsSidebar:       [{ type: 'autogenerated', dirName: 'spells' }],
  npcsSidebar:         [{ type: 'autogenerated', dirName: 'npcs' }],
  questsSidebar:       [{ type: 'autogenerated', dirName: 'quests' }],
  craftsSidebar:       [{ type: 'autogenerated', dirName: 'crafts' }],
  achievementsSidebar: [{ type: 'autogenerated', dirName: 'achievements' }],
  guidesSidebar:       [{ type: 'autogenerated', dirName: 'guides' }],
};

module.exports = sidebars;
